Unbrickable/Models/BackUp.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unbrickable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackUp
    {
        public int id { get; set; }
        public string filename { get; set; }
        public int num_posts { get; set; }
        public System.DateTime date_uploaded { get; set; }
    }
}

Unbrickable/ViewModels/BackUpViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Unbrickable.ViewModels
{
    public class BackUpViewModel
    {
        public int id { get; set; }
        public int num_posts { get; set; }
        public string date { get; set; }
    }
}

Unbrickable/ViewModels/BoardPostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Unbrickable.ViewModels
{
    public class BoardPostViewModel
    {
        public int id { get; set; }
        public int account_id { get; set; }
        public int access_level_id { get; set; }
        public string username { get; set; }
        public string date_posted_text { get; set; }
        public string entry { get; set; }
        public string name { get; set; }
        public string joined_date_text { get; set; }
        public string date_edited_text { get; set; }
        public List<LinkedItemViewModel> linked_items { get; set; }

    }
}

Unbrickable/ViewModels/CartItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Unbrickable.ViewModels
{
    public class CartItemViewModel
    {
        public int id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
    }
}

Unbrickable/ViewModels/NewPostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Unbrickable.ViewModels
{
    public class NewPostViewModel
    {
        public int id { get; set; }
        public string entry { get; set; }
        public IEnumerable<LinkedItemViewModel> linked_items { get; set; }
    }
}

Unbrickable/ViewModels/TransactionDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Unbrickable.ViewModels
{
    public class TransactionDetailViewModel
    {
        public string username { get; set; }
        public IEnumerable<TransactionItemDetailViewModel> transaction_items{ get; set; }
    }
}

Unbrickable/Controllers/AJAXController.cs
using Ganss.XSS;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Unbrickable.Models;
using Unbrickable.ViewModels;

namespace Unbrickable.Controllers
{
    [ValidateInput(false)]
    public class AJAXController : Controller
    {
        private UnbrickableDatabase db = new UnbrickableDatabase();

        public ActionResult GenerateDayList(int? month, int? year)
        {
            if (month == null || year == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int month_val = (int)month;
            int year_val = (int)year;
            List<SelectListItem> days = new List<SelectListItem>();
            for (int i = 1; i <= DateTime.DaysInMonth(year_val, month_val); i++)
            {
                days.Add(new SelectListItem() { Text = i.ToString(), Value = i.ToString() });
            }
            return Json(days, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSalutationList(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gender g = db.Genders.Find(id);
            if (g == null)
            {
                return HttpNotFound();
            }
            List<SelectListItem> Salutations = new List<SelectListItem>();
            foreach (Salutation s in g.Salutations)
            {
                SelectListItem sli = new SelectListItem();
                sli.Text = s.value.ToString();
                sli.Value = s.id.ToString();
                Salutations.Add(sli);
            }
            return Json(Salutations, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EditPost(int? id, int? account_id, string val)
        {
            if (Session["User"] == null || id == null || account_id == null || account_id != Convert.ToInt32(Session["User"]))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                Account a = db.Accounts.Find(Session["User"]);
                Post p = db.Posts.Find(id);
                if (a != null && (Session["Elevation"].Equals("Administrator") || p.id == id))
                {
                    if (p != null)
                    {
                        var sanitizer = new HtmlSanitizer();
                        string sanitized = sanitizer.Sanitize(val);
                        p.entry = HttpUtility.HtmlEncode(sanitized);
                        p.editor_id = a.id;
                        db.SaveChanges();
                        return new HttpStatusCodeResult(HttpStatusCode.OK);
                    }
                    else
                    {
                        return HttpNotFound();
                    }
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }
        }

        [HttpPost]
        public ActionResult DeletePost(int? id, int? account_id)
        {
            if (Session["User"] == null || id == null || account_id == null || account_id != Convert.ToInt32(Session["User"]))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                Account a = db.Accounts.Find(Session["User"]);
                Post p = db.Posts.Find(id);
                if (p == null || a == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    if (Session["Elevation"].Equals("Administrator") || p.account_id == a.id)
                    {
                        db.Posts.Remove(p);
                        db.SaveChanges();
                        return new HttpStatusCodeResult(HttpStatusCode.OK);
                    }
                    else
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                }                
            }
        }

        public ActionResult AddPostSearchFilter(int? num)
        {
            if (num == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                return PartialView("~/Views/Application/EditorTemplates/PostSearchFilter.cshtml", new PostSearchFilter() { num = (int)num });
            }            
        }

        public ActionResult AddUsernameSearchFilter(int? num)
        {
            if (num == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                return PartialView("~/Views/Application/EditorTemplates/UsernameSearchFilter.cshtml", new UsernameSearchFilter() { num = (int)num });
            }
        }

        public ActionResult AddDateSearchFilter(int? num)
        {
            if (num == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                DateSearchFilter dsf = new DateSearchFilter() { num = (int)num };                
                dsf.date = DateTime.Now;
                return PartialView("~/Views/Application/EditorTemplates/DateSearchFilter.cshtml", dsf);
            }
        }

        public ActionResult AddDateRangeSearchFilter(int? num)
        {
            if (num == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                return PartialView("~/Views/Application/EditorTemplates/DateRangeSearchFilter.cshtml", new DateRangeSearchFilter() { num = (int)num, min_date = DateTime.Now, max_date = DateTime.Now });
            }
        }
        
        [HttpPost]
        public ActionResult DeleteItem(int? id)
        {
            if (Session["User"] == null || id == null || !Session["Elevation"].Equals("Administrator"))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                Item i = db.Items.Find(id);
                if (i == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    db.Items.Remove(i);
                    db.SaveChanges();
                    return new HttpStatusCodeResult(HttpStatusCode.OK);
                }
            }
        }

        private int GetIndexOfItem(List<CartItemViewModel> l_civm, int id)
        {
            for (int i = 0; i < l_civm.Count; i++)
            {
                if (l_civm[i].id == id)
                {
                    return i;
                }
            }
            return -1;
        }

        [HttpPost]
        public ActionResult EditItemQuantityInCart(int? id, int? qty)
        {
            List<CartItemViewModel> l_civm = (List<CartItemViewModel>)Session["Cart"];
            
            if (l_civm == null)
            {
                l_civm = new List<CartItemViewModel>();
            }

            if (id == null || qty == null || Session["User"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            int index = GetIndexOfItem(l_civm, (int)id);

            if(index < 0 || index >= l_civm.Count)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            int qnty = (int)qty;            
            
            if(qnty == 0)
            {
                l_civm.RemoveAt(index);
            }
            else
            {
                l_civm[index].quantity = qnty;
            }

            Session["Cart"] = l_civm;
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        public ActionResult DeleteItemQuantityInCart(int? index)
        {
            List<CartItemViewModel> l_civm = (List<CartItemViewModel>)Session["Cart"];
            
            if (index == null || index < 0 || index >= l_civm.Count || Session["User"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            l_civm.RemoveAt((int)index);

            Session["Cart"] = l_civm;
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        public ActionResult GetTransactionDetails(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction t = db.Transactions.Find(id);
            if(t == null)
            {
                return HttpNotFound();
            }
            TransactionDetailViewModel tdvm = new TransactionDetailViewModel();
            List<TransactionItemDetailViewModel> l_tidvm = new List<TransactionItemDetailViewModel>();
            foreach(TransactionItem ti in t.TransactionItems)
            {
                TransactionItemDetailViewModel tidvm = new TransactionItemDetailViewModel();
                tidvm.item_name = ti.item_name;
                tidvm.item_quantity = ti.quantity; ;
                tidvm.item_price = ti.item_price;
                tidvm.total_price = ti.item_price * ti.quantity;
                l_tidvm.Add(tidvm);
            }
            tdvm.username = t.Account.username;
            tdvm.transaction_items = l_tidvm;
            return PartialView("TransactionDetails", tdvm);
        }

        public ActionResult GetFilteredTransactions(string datebefore, string dateafter)
        {

Unbrickable/Views/Shared/BackUp.cshtml
@model Unbrickable.ViewModels.BackUpViewModel


<li onclick="selectedFile = @Model.id;">
    <div class='file rounded cd-popup-trigger'>
        <h1>@Model.num_posts</h1>
        <h2>Posts</h2>
        <h3>@Model.date</h3>
    </div>
    @using (Html.BeginForm("DownloadBackUp/"+Model.id, "Application", null, FormMethod.Post, new { @id = "file_"+Model.id, @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
    }
</li>

Unbrickable/Views/Shared/BoardPost.cshtml
@model Unbrickable.ViewModels.BoardPostViewModel

<li>
    <div class='entry'>
        <div class="entry-container">
            @if (Session["User"] != null && Session["Elevation"] != null && (Convert.ToInt32(Session["User"]) == Model.account_id || Session["Elevation"].Equals("Administrator")))
            {
                <div class='entry-icons'>
                    <div class='general-logo'>
                        <label id='edit-entry' class='pink icon-edit'></label>
                        <label id='edit-confirm' class='pink icon-add hide edit-Post-btn' data-value="@Model.id" data-value2="@Model.account_id"></label>
                    </div>
                    <div class='general-logo delete-Post-btn' data-value="@Model.id" data-value2="@Model.account_id"><label class='pink icon-delete'></label></div>
                </div>
            }
            <div class='username-side'>
                <div class='profile-photo'></div>
                <div class='username-details'>
                    <h2 onclick='window.location="/Application/UserPage/"+@Model.account_id' class="pink">@Model.name</h2>
                    <br>
                    <label class="pink">@Model.joined_date_text</label>
                </div>
            </div>
            <div class='comment-side'>
                <h1 onclick='window.location="/Application/UserPage/"+@Model.account_id'>@Model.username</h1>
                <h2 class="grey">@Model.date_posted_text</h2>
                <div class='entry-comment' id="entry_@Model.id">@Html.Raw(HttpUtility.HtmlDecode(Model.entry))</div>
                <div class='timestamp grey'>@Model.date_edited_text</div>
                @if (Model.linked_items.Count() > 0)
                {
                    <div class='attached-links'>
                        <h2>Linked Items</h2>
                        <ul class='attached-link-container'>
                            @foreach (Unbrickable.ViewModels.LinkedItemViewModel livm in Model.linked_items)
                            {
                                <li onclick="window.location = '/Application/ViewItem?id=' + @livm.id">@livm.item_name</li>
                            }                            
                        </ul>
                    </div>
                }               
            </div>            
        </div>
    </div>
</li>

Unbrickable/Views/Shared/Cart.cshtml
@model IEnumerable<Unbrickable.ViewModels.CartItemViewModel>

<div class="checkout" id='checkout-screen'>
    <div class="checkout-grid">
        <div class="checkout-grid__item sizing-thingy" id="checkout-grid__item--summary">
            <button class="checkout__close checkout__cancel"><i class="icon fa fa-close"></i></button>
            <div class="checkout__total">@String.Format("${0}", Math.Round(Model.Sum(e => e.price * e.quantity),2))</div>
            <button class="checkout__option checkout__option--loud" onclick="$('#checkout_form').submit();">Buy</button>
            <button class="checkout__option checkout__option--silent checkout__cancel">or continue shopping <i class="fa fa-angle-right"></i></button>
            <a class="checkout__button" href="#">
                <!-- Fallback location -->
                <span class="checkout__text">
                    <svg class="checkout__icon" width="60px" height="60px" viewBox="0 0 35 35">
                        <path d="m26.818,19.037l3.607,-10.796c0.181,-0.519 0.044,-0.831 -0.102,-1.037c-0.374,-0.527 -1.143,-0.532 -1.292,-0.532l-20.385,-0.004l-0.544,-2.581c-0.147,-0.609 -0.581,-1.19 -1.456,-1.19h-5.729c-0.594,0 -0.917,0.278 -0.917,0.833v1.49c0,0.537 0.322,0.677 0.938,0.677h4.837l3.702,15.717c-0.588,0.623 -0.908,1.531 -0.908,2.378c0,1.864 1.484,3.582 3.38,3.582c1.79,0 3.132,-1.677 3.35,-2.677h7.21c0.218,1 1.305,2.717 3.349,2.717c1.863,0 3.378,-1.614 3.378,-3.475c0,-1.851 -1.125,-3.492 -3.359,-3.492c-0.929,0 -2.031,0.5 -2.543,1.25h-8.859c-0.643,-1 -1.521,-1.31 -2.409,-1.345l-0.123,-0.655h13.479c1.016,0 1.216,-0.37 1.396,-0.86zm-0.935,3.791c0.701,0 1.27,0.569 1.27,1.27s-0.569,1.27 -1.27,1.27s-1.271,-0.568 -1.271,-1.27c0.001,-0.701 0.57,-1.27 1.271,-1.27zm-12.678,1.27c0,0.709 -0.576,1.286 -1.283,1.286c-0.709,-0.002 -1.286,-0.577 -1.286,-1.286s0.577,-1.286 1.286,-1.286c0.707,0 1.283,0.577 1.283,1.286z" />
                    </svg>
                </span>
                <div id='cart-count'>
                    <label>@Model.Count()</label>
                </div>
            </a>
        </div>
        @foreach (Unbrickable.ViewModels.CartItemViewModel civm in Model)
        {
           @Html.Partial("CartItem", civm)
        }        
        @using (Html.BeginForm("PaymentWithPaypal", "Paypal", null, FormMethod.Get, new { @id = "checkout_form", @enctype = "multipart/form-data" }))
        {
        }
    </div>
</div><!-- /checkout -->

<script>   
    (function () {
        [].slice.call(document.querySelectorAll('.checkout')).forEach(function (el) {
            var openCtrl = el.querySelector('.checkout__button'),
                closeCtrls = el.querySelectorAll('.checkout__cancel');
            specialBox = document.getElementById('checkout-grid__item--summary');
            cartCount = document.getElementById('cart-count');
            screen = $(window).height() - 40;

            openCtrl.addEventListener('click', function (ev) {
                ev.preventDefault();
                classie.add(el, 'checkout--active');
                classie.remove(specialBox, 'sizing-thingy')
                classie.add(specialBox, 'color-thingy')
                classie.add(cartCount, 'invisible')
                $('#checkout-screen').css('height', screen);
            });

            [].slice.call(closeCtrls).forEach(function (ctrl) {
                ctrl.addEventListener('click', function () {
                    classie.remove(el, 'checkout--active');
                    classie.remove(specialBox, 'color-thingy')
                    classie.add(specialBox, 'sizing-thingy')
                    classie.remove(cartCount, 'invisible')
                    $('#checkout-screen').css('height', '120px');
                });
            });
        });
    })();
</script>

Unbrickable/Views/Shared/CartItem.cshtml
@model Unbrickable.ViewModels.CartItemViewModel

<div class="checkout-grid__item">
    @if (Model.image == "")
    {
        <img src="~/Content/img/brick-icon1.png" alt="@Model.name" />
    }
    else
    {
        <img src="@Model.image" alt="@Model.name" />
    }

    <h4>@Model.name</h4><span class="price">@String.Format("${0}", Math.Round(Model.price, 2))</span>
    <h4>Quantity</h4>
    @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class="text-area full-entries checkout-quantity", @id="Cart_"+ Model.id} });
    <button class="checkout-grid__item-remove"><i class="icon fa fa-close"></i></button>

</div>

<script>
    $("#Cart_"+@Model.id).change(function(){
        var id = @Model.id;
        var qty = $("#Cart_"+@Model.id).val();
        $.ajax({
            cache: false,
            type: "Post",
            url: "/AJAX/EditItemQuantityInCart",
            data: { "id": id , "qty": qty}
        }).done(function (data) {
            location.reload();
        });
    });
</script>

Unbrickable/Views/Shared/NewLinkedItem.cshtml
@model Unbrickable.ViewModels.LinkedItemViewModel

<li class='product-thumbs'>
    @Html.CheckBoxFor(x => x.isChecked, new { @class="detailToggle", Name = "linked_items[" + Model.num + "].isChecked" })    
    <div class='item-thumb-photo'>
        @Html.HiddenFor(x => x.id, new { Name = "linked_items[" + Model.num + "].id" })
        <div class='item-thumb'>
            @if (Model.image_src == "")
            {
                <img src="~/Content/img/brick-icon1.png" alt="@Model.item_name" />
            }
            else
            {
                <img src="@Model.image_src" alt="@Model.item_name" />
            }
        </div>
        <label>@Model.item_name</label>
    </div>
</li>

Unbrickable/Views/Shared/NewPost.cshtml
@model Unbrickable.ViewModels.NewPostViewModel

<div class='md-header'>
    <h3 class='element-label'>Add a Message</h3>
</div>
@using (Html.BeginForm("Post", "Application", null, FormMethod.Post, new { @id = "Post_form", @enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()
<div class="message-side">
    <div class='pane component-container'>
        <div class='pane add-session-pane'>   
                @Html.HiddenFor(model => model.id)
                @Html.TextAreaFor(model => model.entry, new { @class = "text-area message-field" })
        </div>
    </div>
    <div class='search-side'>
        <div class='search-header'>
            <h2>Link an item</h2>
        </div>
        <input class='element-label pane search-area' type='text' name='search' value='Search...'>
        <button class='search-button'><span class='pane search-span icon-search'></span></button>

        <div id="rg-gallery" class="rg-gallery">
            <div class="rg-thumbs">
                <!-- Elastislide Carousel Thumbnail Viewer -->
                <div class="es-carousel-wrapper">
                    <div class="es-nav">
                        <span class="es-nav-prev">Previous</span>
                        <span class="es-nav-next">Next</span>
                    </div>
                    <div class="es-carousel">
                        <ul>
                            @foreach (Unbrickable.ViewModels.LinkedItemViewModel livm in Model.linked_items)
                            {
                               @Html.Partial("NewLinkedItem", livm)
                            }                         
                            
                        </ul>
                    </div>
                </div>
                <!-- End Elastislide Carousel Thumbnail Viewer -->
            </div><!-- rg-thumbs -->
        </div><!-- rg-gallery -->
    </div>
</div>
}
<div class='close-trigger-container'>
    <div class='reg-btn modal-btn-set'>
        <ul class='home-nav-controls'>
            <li onclick="$('#Post_form').submit();">
                <div class='vertical-align control-label-container'>
                    <div class='control-label'><nav>Add</nav></div>
                </div>
            </li>

            <li>
                <div class='vertical-align control-label-container'>
                    <div class='control-label md-close'><nav>Cancel</nav></div>
                </div>
            </li>
        </ul>
    </div>

</div>

<script>
    $(".product-thumbs").click(function() {

				var checkbox = $(this).find(":checkbox"),   // keep reference of checkbox
					checked = checkbox.is(":checked");      // check checkbox status
				/*if (checked) {
					$(this).css("color", "#FFF");
					$(this).css("background-color", "#6bccb4");
				} else {
					$(this).css("color", "#6bccb4");
					$(this).css("background-color", "#FFF");
				}*/

				// change checkbox statr
				checkbox.prop("checked", !checked);

			});

			// bind click event  to checkbox
			// to trigger the click to li

			$('.item :checkbox').click(function() {
			  $(this).parent('li').click();
			});
</script>

Unbrickable/Views/Shared/SearchPosts.cshtml
@model List<Unbrickable.ViewModels.SearchCriteria>
<div class='md-header'>
    <label class='element-label'>Search for a Post</label>
</div>

<div class='pane component-container'>
    <div class='pane add-session-pane'>
        <ul class='advanced-filters'>
            <li id="add_Post_filter">
                <label class='filter-label icon-Post'>Filter by Posts</label>
            </li>

            <li id="add_user_filter">
                <label class='filter-label icon-user-entry'>Filter by Users</label>
            </li>

            <li id="add_date_range_filter">
                <label class='filter-label icon-archive'>Filter by Date Range</label>
            </li>

            <li id="add_date_filter">
                <label class='filter-label icon-date'>Filter by Date</label>
            </li>
        </ul>
        <div class='search-filter-container'>
            @using (Html.BeginForm("SearchResults", "Application", null, FormMethod.Get, new { @id = "search_form", @enctype = "multipart/form-data" }))
            {
            <ul class='search-filter-list' id="list_filters">
               @for (int i = 0; i < Model.Count; i++)
               {
                    @Html.EditorFor(model => model[i])
               }
            </ul>
            }
        </div>
    </div>
</div>
<div class='close-trigger-container'>
    <div class='reg-btn modal-btn-set'>
        <ul class='home-nav-controls'>
            <li>
                <div class='vertical-align control-label-container'>
                    <div class='control-label' onclick=" $('#search_form').submit();"><nav>Go</nav></div>
                </div>
            </li>

            <li>
                <div class='vertical-align control-label-container'>
                    <div class='control-label md-close'><nav>Cancel</nav></div>
                </div>
            </li>
        </ul>
    </div>
</div>

<script>
    $('#add_Post_filter').click(function () {
        $.ajax({
            url: '@Url.Action("AddPostSearchFilter", "AJAX")',
            data: { "num": $('#list_filters').children().length },
            type: "GET",
            cache: false,
            success: function (html) {
                $('#list_filters').append(html);
            }
        });
    });
    $('#add_user_filter').click(function () {
        $.ajax({
            url: '@Url.Action("AddUsernameSearchFilter", "AJAX")',
            data: { "num": $('#list_filters').children().length },
            type: "GET",
            cache: false,
            success: function (html) {
                $('#list_filters').append(html);
            }
        });
    });
    $('#add_date_filter').click(function () {
        $.ajax({
            url: '@Url.Action("AddDateSearchFilter", "AJAX")',
            data: { "num": $('#list_filters').children().length },
            type: "GET",
            cache: false,
            success: function (html) {
                $('#list_filters').append(html);
            }
        });
    });
    $('#add_date_range_filter').click(function () {
        $.ajax({
            url: '@Url.Action("AddDateRangeSearchFilter", "AJAX")',
            data: { "num": $('#list_filters').children().length },
            type: "GET",
            cache: false,
            success: function (html) {
                $('#list_filters').append(html);
            }
        });
    });
</script>

Unbrickable/Views/Shared/TransactionContents.cshtml
@model IEnumerable<Unbrickable.ViewModels.TransactionViewModel>

@foreach (Unbrickable.ViewModels.TransactionViewModel tvm in Model)
{
    <tr>
        <th>@tvm.date</th>
        <th class='mid'>@tvm.username</th>
        <th class='mid'>@tvm.name</th>
        <th class='mid'>@String.Format("${0}", Math.Round(tvm.total, 2))</th>
        <th class='mid'><a href="#detailsModal" class="transaction_modal" data-value="@tvm.id">Details...</a></th>
        <th>@tvm.transaction_status</th>
    </tr>
}
<script>
    $('.transaction_modal').click(function () {
        var tr_id = $(this).data("value");
        $.ajax({
            url: '@Url.Action("GetTransactionDetails", "AJAX")',
            data: { "id": tr_id },
            type: "GET",
            cache: false,
            success: function (html) {
                $('#detail_loc').html(html);
            }
        });
    });
</script>

Unbrickable/Views/Shared/TransactionDetails.cshtml
@model Unbrickable.ViewModels.TransactionDetailViewModel

    <h3>@Model.username</h3>
    <div class ="modal-container">
        <table class='transactions-table'>
            <tbody>
                <tr>
                    <th class='transactions-table-header'>Items</th>
                    <th class='transactions-table-header'>Quantity</th>
                    <th class='transactions-table-header'>Price</th>
                    <th class='transactions-table-header'>Total</th>
                </tr>
                @foreach (Unbrickable.ViewModels.TransactionItemDetailViewModel tidvm in Model.transaction_items)
                {
                    <tr>
                        <th>@tidvm.item_name</th>
                        <th class='mid'>@tidvm.item_quantity</th>
                        <th class='mid'>@String.Format("${0}", Math.Round(tidvm.item_price,2))</th>
                        <th>@String.Format("${0}", Math.Round(tidvm.total_price,2))</th>
                    </tr>
                }           
            </tbody>
        </table>
    </div>

Unbrickable/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
	<head>
        <link rel='stylesheet' type='text/css' href='@Url.Content("~/Content/css/tabstyles.css")'>
        <link rel='stylesheet' type='text/css' href='@Url.Content("~/Content/css/tabs.css")'>
        <link rel='stylesheet' type='text/css' href='@Url.Content("~/Content/css/component.css")'>
        <link rel='stylesheet' type='text/css' href='@Url.Content("~/Content/css/confirmation-box.css")'>
        <link rel='stylesheet' type='text/css' href='@Url.Content("~/Content/css/layout.css")'>
        <link rel='stylesheet' type='text/css' href='@Url.Content("~/Content/css/checkout-boxes.css")'>
        <link rel="stylesheet" type="text/css" href='@Url.Content("~/Content/fonts/font-awesome-4.2.0/css/font-awesome.min.css")'>
        <script type='text/javascript' src='@Url.Content("~/Scripts/jquery-1.11.1.min.js")'></script>
        <script type='text/javascript' src='@Url.Content("~/Scripts/jquery-ui.js")'></script>
        <script type='text/javascript' src='@Url.Content("~/Scripts/inputmask.js")'></script>
        <script type='text/javascript' src='@Url.Content("~/Scripts/jquery.inputmask.js")'></script>
        <script type='text/javascript' src='@Url.Content("~/Scripts/inputmask.regex.extensions.js")'></script>
        <script type='text/javascript' src='@Url.Content("~/Scripts/jquery.form.min.js")'></script>
        <script type='text/javascript' src="@Url.Content("~/Scripts/classie.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/si.files.js")"></script>
		@RenderSection("Headers", false)
        <title></title>
	</head>
	
	<body>
        <div class='container'>
            @RenderBody()
        </div>
	</body>
</html>